print('Descubra a tabuada de um número: ')
t = int(input('Digite um número inteiro: '))
print('A tabuada de {} é:\n'.format(t))
# print(t * 1, '\n', t * 2, '\n', t * 3, '\n', t * 4, '\n', t * 5, '\n', t * 6, '\n', t * 7, '\n', t * 8, '\n', t * 9, '\n', t * 10)
print('-' * 14)
print('{} * {:2} = {}'.format(t, 1, (t * 1)))
print('{} * {:2} = {}'.format(t, 2, (t * 2)))
print('{} * {:2} = {}'.format(t, 3, (t * 3)))
print('{} * {:2} = {}'.format(t, 4, (t * 4)))
print('{} * {:2} = {}'.format(t, 5, (t * 5)))
print('{} * {:2} = {}'.format(t, 6, (t * 6)))
print('{} * {:2} = {}'.format(t, 7, (t * 7)))
print('{} * {:2} = {}'.format(t, 8, (t * 8)))
print('{} * {:2} = {}'.format(t, 9, (t * 9)))
print('{} * {:2} = {}'.format(t, 10, (t * 10)))
print('-' * 14)
